---
userShell: /bin/bash

defaultGroups:
    - name:      wheel
      mustExist: true
      addUsers:  true

doAutologin:      false
setRootPassword:  false

# Collect hostname on the users page.
hostname:
    location:       /etc/hostname
    writeHostsFile: true
    template:       "kyth"

# Minimal password policy — bootc image already enforces nothing.
passwordRequirements:
    minLength:  1
    maxLength:  -1

allowWeakPasswords: true
