---
# Show support/issues URLs in the welcome page.
showSupportUrl:      true
showKnownIssuesUrl:  true
showReleaseNotesUrl: false
showDonateUrl:       false

# System requirements checked on the welcome page.
requirements:
    requiredStorage:   20    # GiB minimum free disk space
    requiredRam:       2     # GiB minimum RAM
    internetRequired:  false  # OCI image is bundled in the ISO squashfs
    firmwareType:      both  # BIOS and UEFI supported
